# Use root/example as user/password credentials
version: '3.1'

services:


  mysql:
    image: mysql:5.7.20
    container_name: s_mysql
   # command: --default-authentication-plugin=mysql_native_password
   # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
     - s-db-data:/var/lib/mysql
    networks:
     s_network:

  web:
    build: './php/'
    container_name: php_web
    image: php:7.2.2-apache
    depends_on:
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html/
    networks:
     s_network:
  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    container_name: s_phpmyadmin
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 8090:80
    links: 
      - mysql:db
    networks:
     s_network:



networks: 
  s_network:

volumes:   
  s-db-data:
 