FROM php:7.2.2-apache
#RUN apk update; \
#    apk upgrade;
RUN apt-get update && apt-get install -y mysql-client
RUN docker-php-ext-install mysqli
RUN docker-php-ext-enable mysqli
#COPY src/ /var/www/html/
